[2025-03-16 06:49:55,620] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: assignment.task_two 2025-03-15T00:00:00+00:00 [queued]>
[2025-03-16 06:49:55,642] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: assignment.task_two 2025-03-15T00:00:00+00:00 [queued]>
[2025-03-16 06:49:55,643] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2025-03-16 06:49:55,643] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2025-03-16 06:49:55,644] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2025-03-16 06:49:55,652] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): task_two> on 2025-03-15T00:00:00+00:00
[2025-03-16 06:49:55,656] {standard_task_runner.py:52} INFO - Started process 181 to run task
[2025-03-16 06:49:55,659] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'assignment', 'task_two', '2025-03-15T00:00:00+00:00', '--job-id', '42', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/assignment.py', '--cfg-path', '/tmp/tmpbbhflqxo', '--error-file', '/tmp/tmpggrp8lz5']
[2025-03-16 06:49:55,659] {standard_task_runner.py:77} INFO - Job 42: Subtask task_two
[2025-03-16 06:49:55,695] {logging_mixin.py:104} INFO - Running <TaskInstance: assignment.task_two 2025-03-15T00:00:00+00:00 [running]> on host 4ecec8cb0ca2
[2025-03-16 06:49:55,753] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=assignment
AIRFLOW_CTX_TASK_ID=task_two
AIRFLOW_CTX_EXECUTION_DATE=2025-03-15T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-03-15T00:00:00+00:00
[2025-03-16 06:49:55,755] {python.py:151} INFO - Done. Returned value was: None
[2025-03-16 06:49:55,764] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=assignment, task_id=task_two, execution_date=20250315T000000, start_date=20250316T064955, end_date=20250316T064955
[2025-03-16 06:49:55,796] {taskinstance.py:1265} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-16 06:49:55,833] {local_task_job.py:151} INFO - Task exited with return code 0
